### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by KarbitsCode** [frypan05/chase#1]
Hello,

I see you trying to push this package to winget, do you need any help?

Thanks.

**Comment by frypan05** [comment]
Hey,
Actually I'm just testing my application with Docker right now. I have to add a couple of .dll files to the installer, then I'll update the PR.
Thanks for kind gesture, appreciate it.

**Comment by KarbitsCode** [comment]
If this was compiled using GCC, you can try `-static` compiler flag to "bundle" those DLLs into your app so it will not require external dependency files.

**Comment by frypan05** [comment]
Thanks a ton! I'll try compiling the file with the static flag.

**Comment by KarbitsCode** [comment]
Also, can you push the source code to this repo? Just so I can understand what your application does.
If not, it's fine 👍

**Comment by KarbitsCode** [comment]
> Also, can you push the source code to this repo?

cc @frypan05
